export type ThemeName = 'dark' | 'light' | 'custom';

export interface ThemeTokens {
  'bg':                string;
  'surface':           string;
  'surface-raised':    string;
  'surface-overlay':   string;
  'text':              string;
  'text-muted':        string;
  'text-subtle':       string;
  'primary':           string;
  'primary-hover':     string;
  'secondary':         string;
  'secondary-hover':   string;
  'accent':            string;
  'accent-hover':      string;
  'success':           string;
  'success-subtle':    string;
  'warning':           string;
  'warning-subtle':    string;
  'danger':            string;
  'danger-subtle':     string;
  'info':              string;
  'info-subtle':       string;
  'presence-online':   string;
  'presence-idle':     string;
  'presence-dnd':      string;
  'presence-offline':  string;
  'stroke':            string;
  'stroke-strong':     string;
  'focus-ring':        string;
  'input':             string;
  'scrollbar':         string;
  'scrollbar-thumb':   string;
  'on-primary':        string;
  'on-secondary':      string;
  'on-accent':         string;
  'on-success':        string;
  'on-warning':        string;
  'on-danger':         string;
  'on-info':           string;
}
